spring:
  datasource:
    url: jdbc:h2:./.local-db/customers-liquibase
    username: sa
    password: ''
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
  h2:
    console:
      enabled: true
application:
  cors:
    enabled: true
    allowed-origins:
      - '*.swagger.io'
      - 'localhost:8080'
    allow-credentials: false