-- changeset diff:20251107-1
CREATE TABLE ADDRESSES (
                         UUID UUID NOT NULL,
                         CITY VARCHAR(255),
                         NUMBER VARCHAR(255),
                         STREET VARCHAR(255),
                         ZIP VARCHAR(255),
                         CONSTRAINT PK_ADDRESSES PRIMARY KEY (UUID)
);

-- changeset diff:20251107-2
ALTER TABLE CUSTOMERS ADD COLUMN ADDRESS_UUID UUID;

-- changeset diff:20251107-3
ALTER TABLE CUSTOMERS ADD CONSTRAINT C_CUSTOMERS_ADDRESS UNIQUE (ADDRESS_UUID);

-- changeset diff:20251107-4
ALTER TABLE CUSTOMERS ADD CONSTRAINT FK_CUSTOMERS_ADDRESS FOREIGN KEY (ADDRESS_UUID)
  REFERENCES ADDRESSES (UUID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT;