-- liquibase formatted sql

-- changeset ueberfuhr:1781091930390-1 splitStatements:false
CREATE TABLE CUSTOMERS (UUID UUID NOT NULL, BIRTH_DATE date NOT NULL, NAME VARCHAR(255) NOT NULL, STATE VARCHAR(255), CONSTRAINT CONSTRAINT_6 PRIMARY KEY (UUID));

